### ISSUE TITLE
NoMethodError: undefined method `model_for_authorization=' 

### ISSUE THREAD

**Issue by warrior1724** [605data/strongbolt#33]
When I try to start resque  with rake environment resque:work
it can't find model_for_authorization= method.

When I try start application with puma there are no errors

Strongbolt seems to load corectly

===
NoMethodError: undefined method `model_for_authorization=' for Strongbolt::SecurityController:Class
/var/lib/gems/2.3.0/bundler/gems/strongbolt-8d9b53965754/app/controllers/strongbolt/security_controller.rb:3:in `<class:SecurityController>'
/var/lib/gems/2.3.0/bundler/gems/strongbolt-8d9b53965754/app/controllers/strongbolt/security_controller.rb:2:in `<module:Strongbolt>'
/var/lib/gems/2.3.0/bundler/gems/strongbolt-8d9b53965754/app/controllers/strongbolt/security_controller.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
/var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
/var/lib/gems/2.3.0/gems/resque-1.27.4/lib/resque/tasks.rb:45:in `each'
/var/lib/gems/2.3.0/gems/resque-1.27.4/lib/resque/tasks.rb:45:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => resque:work => resque:preload

**Comment by tobithiel** [comment]
I'm not familiar with resque. Sounds like Strongbolt isn't being loaded properly through resque. Make sure `config/environment` is being loaded when you run resque.

**Comment by warrior1724** [comment]
@tobithiel - resque is started with
VERBOSE=1 QUEUE=* RAILS_ENV=development bundle exec rake environment resque:work
it load environment (as described in resque documentation)

any advice ? 
how to debug Strongbolt loading and catch where error is?

**Comment by tobithiel** [comment]
This particular error suggests `lib/strongbolt.rb` or `ActionController` wasn't loaded. The method `model_for_authorization=` is defined in `Strongbolt::BoltedController`, which gets added to every controller right here: https://github.com/605data/strongbolt/blob/master/lib/strongbolt.rb#L43

You'll need to find out why `Strongbolt::BoltedController` isn't being added to `ActionController::Base`.

**Comment by tobithiel** [comment]
I'm gonna close this for now, as we haven't heard back from you. But if you have more information or issues with this, please reopen it.
