### ISSUE TITLE
Q: how to redirect current_user to errors_path if access denied?

### ISSUE THREAD

**Issue by matissg** [605data/strongbolt#43]
I'm trying to figure out how to tweak these few lines from [/config/initializers/strongbolt.rb](https://github.com/605data/strongbolt_example/blob/master/config/initializers/strongbolt.rb) 
```
config.access_denied do |user, instance, action, request|
  Rails.logger.warn "User #{user.try :id} was refused to perform #{action} on #{instance.try :inspect} with request #{request}"
end
```
to have `current_user` to be redirected to some `errors_path` if access is denied? Basically I would like to redirect to my ErrorsController which would render error message saying something like "Access denied. Ask for help to your profile Admin."

Thank you for any help.

**Comment by tobithiel** [comment]
Strongbolt throws a `Strongbolt::Unauthorized` exception in that case, so you should just be able to use Rails application controller to do that: http://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html

**Comment by matissg** [comment]
@tobithiel  Thank you for explaining. It seems to be working as I put it my ApplicationController something like this:

```
rescue_from Strongbolt::Unauthorized, with: :strongbolt_unauthorized

private

  def strongbolt_unauthorized
    redirect_to errors_path
  end
```
