### ISSUE TITLE
How can i set different capabilities on same model but different :id 

### ISSUE THREAD

**Issue by jaydave** [605data/strongbolt#47]
I have this use case where I want to set RUD (read, update, delete) capabilities for Model id 1 but want to just give read capability on Model id 2 for same user. Can you please help in how to achieve this ?

**Comment by tobithiel** [comment]
@jaydave If you have/add a `user_id` to the model, you can model it using ownership of the model. (RUD capabilities if the user owns the model, R capability if the user does _not_ own the model).

**Comment by tobithiel** [comment]
@jaydave Yes, that's what I meant 😄

**Comment by jaydave** [comment]
@tobithiel thanks for help.
