### ISSUE TITLE
Undefined methods

### ISSUE THREAD

**Issue by kinsomicrote** [605data/strongbolt#49]
When I create a new user, the user does not automatically have the methods `capabilities`, `roles`, `can?` assigned to it.
This is only available to users that were created using the seed file.
One more thing, when I change a user's capability for action, calling `.can?` on the user and passing the action returns as false.
Could I be doing something wrong?

Thanks.

**Comment by tobithiel** [comment]
@kinsomicrote The methods are coming from the [UserAbilities](https://github.com/605data/strongbolt/blob/master/lib/strongbolt/user_abilities.rb) module. It's automatically included into your configured user class here [here](https://github.com/605data/strongbolt/blob/ee970136776c28f8e6a81a7453b3b56eeb02de74/lib/strongbolt.rb#L115). It sounds like Strongbolt isn't setup correctly. I would encourage you to check out [Getting Started](https://github.com/605data/strongbolt#getting-started) and [strongbolt-example](https://github.com/605data/strongbolt_example) to check your setup.
